import { michroma } from '@/fonts'
import type { Metadata } from 'next'
import './globals.css'
import 'swiper/css'
import 'swiper/css/navigation'
import 'aos/dist/aos.css'
import Header from '@/components/layout/header'
import Footer from '@/components/layout/footer'
import i18nConfig from '@/i18nConfig'
import { dir } from 'i18next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export function generateStaticParams() {
    return i18nConfig.locales.map(locale => ({ locale }))
}

export default function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode
    params: { locale: string }
}>) {
    return (
        <html lang={locale} dir={dir(locale)}>
            <body className={`${michroma.className}`}>
                <div className="grid min-h-screen grid-cols-1">
                    <Header />
                    {children}
                    <Footer />
                </div>
                <div id="modals" />
            </body>
        </html>
    )
}
