import { michroma } from '@/fonts'
import type { Metadata } from 'next'
import './globals.css'
import 'swiper/css'
import 'swiper/css/navigation'
import 'aos/dist/aos.css'
import Header from '@/components/layout/header'
import Footer from '@/components/layout/footer'
import i18nConfig from '@/i18nConfig'
import { dir } from 'i18next'
import TranslationsProvider from '@/components/providers/locales'
import initTranslations from '../i18n'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export function generateStaticParams() {
    return i18nConfig.locales.map(locale => ({ locale }))
}

const namespaces = ['common', 'contacts', 'homepage']
export default async function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode
    params: { locale: string }
}>) {
    const { resources } = await initTranslations(locale, namespaces)
    return (
        <html lang={locale} dir={dir(locale)}>
            <body className={`${michroma.className}`}>
                <TranslationsProvider namespaces={namespaces} locale={locale} resources={resources}>
                    <div className="grid min-h-screen grid-cols-1">
                        <Header />
                        {children}
                        <Footer />
                    </div>
                    <div id="modals" />
                </TranslationsProvider>
            </body>
        </html>
    )
}
